# Auto-fit window to content aspect ratio
autofit-larger=80%x80%
autofit-smaller=30%x30%

# --- ÂM LƯỢNG (Volume) ---
volume-max=100
ao=pipewire,pulse
save-position-on-quit=yes

# --- TĂNG TỐC PHẦN CỨNG & HÌNH ẢNH ---
hwdec=auto
vo=gpu
# Bỏ profile=gpu-hq vì nó quá nặng đối với iGPU (gây lag)

# --- GIAO DIỆN UOSC (Tắt UI cũ đi) ---
osc=no
osd-bar=no
border=no

# --- PHỤ ĐỀ (Subtitles) ---
sub-auto=fuzzy
sub-font-size=40
sub-color="#FFFFFFFF"
sub-border-color="#FF000000"
sub-border-size=2
sub-shadow-offset=1
sub-shadow-color="#33000000"
slang=vi,vie,vn,en,eng
alang=ja,jp,jpn,en,eng
