# --- DISPLAY SETTINGS ---
# Tự động xuất hiện ở giữa màn hình đang nhận Focus (Laptop eDP-1 hoặc Màn rời DP-1)
# output=DP-1
font=JetBrainsMono-Regular:size=10
dpi-aware=yes
prompt="   "
icon-theme=Qogir-dark
icons-enabled=yes
filter-desktop=yes
match-mode=fzf

# --- WINDOW LAYOUT ---
anchor=center
lines=8
width=35
tabs=8
horizontal-pad=30
vertical-pad=20
inner-pad=8
image-size-ratio=.2

# --- GENERAL SETTINGS ---
terminal=footclient -e
exit-on-keyboard-focus-loss=yes
cache=/home/mr-thai/.cache/fuzzel

# --- COLORS ---
[colors]
background=1e1e2ee6
text=cdd6f4ff
prompt=cba6f7ff
input=cdd6f4ff
match=f38ba8ff
selection-match=f38ba8ff
selection=313244ff
selection-text=cdd6f4ff
border=cba6f7ff

[border]
width=2
radius=8

[dmenu]

[key-bindings]
execute-or-next=none
custom-1=Tab
