[manager]
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
tab_size = 4
max_width = 800
max_height = 800
cache_dir = ""
image_filter = "triangle"
image_quality = 75

[opener]
edit = [
    { run = 'nvim "$@"', block = true }
]
play = [
    { run = 'mpv "$@"', orphan = true }
]
open = [
    { run = 'xdg-open "$@"', orphan = true }
]
word = [
    { run = 'abiword "$@"', orphan = true, desc = "Quick Read Word" }
]
excel = [
    { run = 'gnumeric "$@"', orphan = true, desc = "Quick Read Excel" }
]
pdf = [
    { run = 'zathura "$@"', orphan = true }
]
image = [
    { run = 'imv "$@"', orphan = true }
]
extract = [
    { run = 'ouch decompress "$@"', desc = "Extract here", block = true }
]

[open]
rules = [
    { url = "*/", use = [ "edit", "open" ] },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = [ "image", "open" ] },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { mime = "application/zip", use = "extract" },
    { mime = "application/x-tar", use = "extract" },
    { mime = "application/x-bzip2", use = "extract" },
    { mime = "application/x-gzip", use = "extract" },
    { mime = "application/x-7z-compressed", use = "extract" },
    { mime = "application/x-rar", use = "extract" },
    { mime = "application/pdf", use = [ "pdf", "open" ] },
    { mime = "application/epub+zip", use = [ "pdf", "open" ] },
    { mime = "image/vnd.djvu", use = [ "pdf", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = [ "word", "open" ] },
    { mime = "application/msword", use = [ "word", "open" ] },
    { mime = "application/rtf", use = [ "word", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = [ "excel", "open" ] },
    { mime = "application/vnd.ms-excel", use = [ "excel", "open" ] },
    { mime = "text/csv", use = [ "excel", "open" ] },
    { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = "edit" },
    { url = "*.docx", use = [ "word", "open" ] },
    { url = "*.doc", use = [ "word", "open" ] },
    { url = "*.xlsx", use = [ "excel", "open" ] },
    { url = "*.xls", use = [ "excel", "open" ] },
    { url = "*.csv", use = [ "excel", "open" ] },
    { mime = "inode/empty", use = "edit" },
    { url = "*", use = "open" },
]

[plugin]
prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" },
]
prepend_previewers = [
    { mime = "font/*", run = "font" },
    { mime = "application/x-bittorrent", run = "mediainfo" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/zip", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "video/*", run = "mediainfo" },
    { mime = "audio/*", run = "mediainfo" },
]


