[manager]
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
tab_size = 4
max_width = 800
max_height = 800
cache_dir = ""
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15

[opener]
edit = [
    { run = 'nvim "$@"', block = true }
]
play = [
    { run = 'mpv "$@"', orphan = true }
]
open = [
    { run = 'xdg-open "$@"', orphan = true }
]
office = [
    { run = 'onlyoffice-desktopeditors "$@"', orphan = true, desc = "Open with OnlyOffice" }
]
pdf = [
    { run = 'zathura "$@"', orphan = true }
]
image = [
    { run = 'imv "$@"', orphan = true }
]
extract = [
    { run = 'ouch decompress "$@"', desc = "Extract here", block = true }
]

[open]
rules = [
    { url = "*/", use = [ "edit", "open" ] },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = [ "image", "open" ] },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { mime = "application/zip", use = "extract" },
    { mime = "application/x-tar", use = "extract" },
    { mime = "application/x-bzip2", use = "extract" },
    { mime = "application/x-gzip", use = "extract" },
    { mime = "application/x-7z-compressed", use = "extract" },
    { mime = "application/x-rar", use = "extract" },
    { mime = "application/pdf", use = [ "pdf", "open" ] },
    { mime = "application/epub+zip", use = [ "pdf", "open" ] },
    { mime = "image/vnd.djvu", use = [ "pdf", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = [ "office", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = [ "office", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.presentationml.presentation", use = [ "office", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.template", use = [ "office", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.template", use = [ "office", "open" ] },
    { mime = "application/vnd.openxmlformats-officedocument.presentationml.slideshow", use = [ "office", "open" ] },
    { mime = "application/vnd.ms-word.document.macroEnabled.12", use = [ "office", "open" ] },
    { mime = "application/vnd.ms-excel.sheet.macroEnabled.12", use = [ "office", "open" ] },
    { mime = "application/vnd.ms-powerpoint.presentation.macroEnabled.12", use = [ "office", "open" ] },
    { mime = "application/msword", use = [ "office", "open" ] },
    { mime = "application/vnd.ms-excel", use = [ "office", "open" ] },
    { mime = "application/vnd.ms-powerpoint", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.text", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.spreadsheet", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.presentation", use = [ "office", "open" ] },
    { mime = "application/rtf", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.text-template", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.spreadsheet-template", use = [ "office", "open" ] },
    { mime = "application/vnd.oasis.opendocument.presentation-template", use = [ "office", "open" ] },
    { mime = "application/x-hwp", use = [ "office", "open" ] },
]

[plugin]
prepend_previewers = [
    { mime = "font/*", run = "fontimage" },
    { mime = "application/x-bittorrent", run = "mediainfo" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/zip", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "video/*", run = "mediainfo" },
    { mime = "audio/*", run = "mediainfo" },
    { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", run = "office" },
    { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", run = "office" },
    { mime = "application/vnd.openxmlformats-officedocument.presentationml.presentation", run = "office" },
    { mime = "application/vnd.oasis.opendocument.text", run = "office" },
    { mime = "application/vnd.oasis.opendocument.spreadsheet", run = "office" },
    { mime = "application/vnd.oasis.opendocument.presentation", run = "office" },
]


