context.properties = {
    # Tần số lấy mẫu mặc định
    default.clock.rate          = 48000

    # Cho phép chuyển đổi tần số động (Bit-Perfect / Native Playback)
    # Thêm 88200 và 176400 là bội số của 44100 (chuẩn đĩa CD) 
    # giúp nghe nhạc lossless chất lượng cao nhất mà không bị méo tiếng do resample chéo.
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]

    # Kích thước bộ đệm (độ trễ) mặc định
    default.clock.quantum       = 1024
    default.clock.min-quantum   = 32
    default.clock.max-quantum   = 8192
}

stream.properties = {
    # Sử dụng thuật toán SoX (Sox Resampler) chất lượng audiophile huyền thoại
    # thay vì thuật toán mặc định speex.
    resample.algorithm = "soxr"

    # Đặt độ chính xác chất lượng cao nhất cho thuật toán
    resample.quality   = 10
}


